# Generated by Django 5.1.4 on 2024-12-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voiceclone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectMaterial',
        ),
    ]
